### ISSUE TITLE
Why the global position and orientation is different from the original bvh ?

### ISSUE THREAD

**Issue by hosseinfeiz** [heyuanYao-pku/MoConVQ#4]
Hi, Thanks for sharing your work. I was wondering why the physics optimized output motion has different orientation and position from the original bvh file and how it can be fixed. 
Thanks

**Comment by heyuanYao-pku** [comment]
Hi. This is because the input of the policy is the local pose that doesn't contain any global information, so the character will try to reconstruct the local pose without the global position and orientation. 
One option is to move and rotate the entire bvh file. While for long motions, it will drift from the original motion because there is no feedback control on the global information.

**Comment by hosseinfeiz** [comment]
Thanks. I will look into it
